name: CI
on: push
jobs:
  lint-server:
    name: Lint Server
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: 14
    - name: Install dependencies 
      run: npm i
      working-directory: server
    - name: Lint
      run: npm run lint
      working-directory: server
  lint-client:
    name: Lint Client
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: 14
    - name: Install Vue CLI
      run: sudo npm i -g @vue/cli-service
    - name: Install dependencies 
      run: npm i
      working-directory: client
    - name: Lint
      run: npm run lint
      working-directory: client